import { ProfileFormData } from "./types";
export const doctorProfiles: (ProfileFormData & { id: string })[] = [
  {
    id: "56074539-f0d2-46b0-973d-3694f39dfcd1",
    firstName: "Rajesh",
    lastName: "Sharma",
    mobile: "+919876543210",
    email: "dr.rajesh@heartcare.com",
    clinicName: "Apex Heart Clinic",
    address: "123 MG Road",
    area: "Connaught Place",
    city: "New Delhi",
    pincode: "110001",
    state: "Delhi",
    council: "Delhi Medical Council",
    specialty: "Cardiology",
    experience: "15",
    other_qualification: "FACC",
    qualifications: [
      { degree: "MBBS", college: "AIIMS New Delhi", completion_year: "2005" },
      { degree: "MD - Cardiology", college: "PGI Chandigarh", completion_year: "2009" }
    ],
    professionals: [
      { institute: "Max Super Speciality Hospital", designation: "Senior Consultant", experience: "2012-Present" }
    ],
    registration_number: "DMC-12345",
    registration_year: "2005",
    online_fee: "1000",
    clinic_fee: "1500",
    show_fees_on_app: true,
    online_booking_window: "30",
    clinic_booking_window: "15",
    languages: ["English", "Hindi"],
    otherLanguage: "Punjabi",
    bio: "Experienced cardiologist specializing in interventional cardiology and preventive heart care.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-1234-5678-9012",
    hpid: "HPID123456789",
    registered_date: "2023-01-10",
    account_status: "active",
    application_status: "approve",
    commission: 20
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    firstName: "Priya",
    lastName: "Nair",
    mobile: "+919811223344",
    email: "dr.priya@childcare.in",
    clinicName: "Little Stars Pediatric Hub",
    address: "45, Jubilee Hills",
    area: "Road No. 36",
    city: "Hyderabad",
    pincode: "500033",
    state: "Telangana",
    council: "Telangana State Medical Council",
    specialty: "Pediatrics",
    experience: "10",
    other_qualification: "FIAP",
    qualifications: [
      { degree: "MBBS", college: "Osmania Medical College", completion_year: "2012" },
      { degree: "DCH", college: "CMC Vellore", completion_year: "2015" }
    ],
    professionals: [
      { institute: "Rainbow Children's Hospital", designation: "Consultant Pediatrician", experience: "2016-Present" }
    ],
    registration_number: "TSMC-67890",
    registration_year: "2012",
    online_fee: "700",
    clinic_fee: "1000",
    show_fees_on_app: true,
    online_booking_window: "14",
    clinic_booking_window: "7",
    languages: ["English", "Telugu", "Hindi"],
    otherLanguage: "Malayalam",
    bio: "Dedicated pediatrician focused on newborn care, childhood immunizations, and developmental growth.",
    app_appointment_token_start: "101",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-9876-5432-1098",
    hpid: "HPID987654321",
    registered_date: "2023-03-14",
    account_status: "inactive",
    application_status: "approve",
    commission: 20
  },
  {
    id: "c3d4e5f6-7890-abcd-ef12-34567890abcd",
    firstName: "Amit",
    lastName: "Patel",
    mobile: "+919722334455",
    email: "dr.amit@skinclinic.com",
    clinicName: "ClearSkin & Laser Clinic",
    address: "78, CG Road",
    area: "Navrangpura",
    city: "Ahmedabad",
    pincode: "380009",
    state: "Gujarat",
    council: "Gujarat Council of Medical Registration",
    specialty: "Dermatology",
    experience: "8",
    other_qualification: "FAM",
    qualifications: [
      { degree: "MBBS", college: "B.J. Medical College", completion_year: "2014" },
      { degree: "MD - Dermatology", college: "KEM Hospital Mumbai", completion_year: "2018" }
    ],
    professionals: [
      { institute: "Sterling Hospitals", designation: "Consultant Dermatologist", experience: "2019-Present" }
    ],
    registration_number: "GMR-11223",
    registration_year: "2014",
    online_fee: "800",
    clinic_fee: "1200",
    show_fees_on_app: true,
    online_booking_window: "20",
    clinic_booking_window: "10",
    languages: ["English", "Gujarati", "Hindi"],
    otherLanguage: "",
    bio: "Expert in clinical dermatology, aesthetic procedures, and advanced laser treatments.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-4321-8765-4321",
    hpid: "HPID456789123",
    registered_date: "2023-05-20",
    account_status: "inactive",
    application_status: "pending",
    commission: 20
  },
  {
    id: "d4e5f678-90ab-cdef-1234-567890abcdef",
    firstName: "Vikram",
    lastName: "Singh",
    mobile: "+919988776655",
    email: "dr.vikram@orthocare.org",
    clinicName: "Advanced Bone & Joint Clinic",
    address: "12, Malviya Nagar",
    area: "JLN Marg",
    city: "Jaipur",
    pincode: "302017",
    state: "Rajasthan",
    council: "Rajasthan Medical Council",
    specialty: "Orthopedics",
    experience: "14",
    other_qualification: "MNAMS",
    qualifications: [
      { degree: "MBBS", college: "SMS Medical College", completion_year: "2008" },
      { degree: "MS - Orthopedics", college: "AIIMS New Delhi", completion_year: "2012" }
    ],
    professionals: [
      { institute: "Fortis Escorts Jaipur", designation: "Senior Orthopedic Surgeon", experience: "2015-Present" }
    ],
    registration_number: "RMC-44556",
    registration_year: "2008",
    online_fee: "900",
    clinic_fee: "1500",
    show_fees_on_app: true,
    online_booking_window: "15",
    clinic_booking_window: "5",
    languages: ["English", "Hindi"],
    otherLanguage: "Rajasthani",
    bio: "Specializing in joint replacement surgeries, arthroscopy, and complex trauma management.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-5566-7788-9900",
    hpid: "HPID789123456",
    registered_date: "2023-06-01",
    account_status: "active",
    application_status: "approve",
    commission: 20
  },
  {
    id: "e5f67890-abcd-ef12-3456-7890abcdef12",
    firstName: "Ananya",
    lastName: "Sen",
    mobile: "+919833445566",
    email: "dr.ananya@womenshealth.in",
    clinicName: "Gynae Care & Maternity Center",
    address: "56, Park Street",
    area: "Central Kolkata",
    city: "Kolkata",
    pincode: "700016",
    state: "West Bengal",
    council: "West Bengal Medical Council",
    specialty: "Obstetrics & Gynecology",
    experience: "12",
    other_qualification: "MRCOG",
    qualifications: [
      { degree: "MBBS", college: "Medical College Kolkata", completion_year: "2010" },
      { degree: "MS - OBG", college: "IPGME&R Kolkata", completion_year: "2014" }
    ],
    professionals: [
      { institute: "Apollo Gleneagles Hospitals", designation: "Consultant", experience: "2016-Present" }
    ],
    registration_number: "WBMC-77889",
    registration_year: "2010",
    online_fee: "1000",
    clinic_fee: "1200",
    show_fees_on_app: false,
    online_booking_window: "30",
    clinic_booking_window: "10",
    languages: ["English", "Bengali", "Hindi"],
    otherLanguage: "",
    bio: "Compassionate gynecologist specializing in high-risk pregnancies, laparoscopic surgeries, and fertility care.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-2233-4455-6677",
    hpid: "HPID321654987",
    registered_date: "2023-07-12",
    account_status: "suspended",
    application_status: "reject",
    commission: 20
  },
  {
    id: "f67890ab-cdef-1234-5678-90abcdef1234",
    firstName: "Rohan",
    lastName: "Deshmukh",
    mobile: "+919922113344",
    email: "dr.rohan@neuroclinic.net",
    clinicName: "Brain & Spine Neuro Care",
    address: "89, FC Road",
    area: "Deccan Gymkhana",
    city: "Pune",
    pincode: "411004",
    state: "Maharashtra",
    council: "Maharashtra Medical Council",
    specialty: "Neurology",
    experience: "16",
    other_qualification: "FRCP",
    qualifications: [
      { degree: "MBBS", college: "Grant Government Medical College", completion_year: "2004" },
      { degree: "DM - Neurology", college: "NIMHANS Bengaluru", completion_year: "2010" }
    ],
    professionals: [
      { institute: "Ruby Hall Clinic", designation: "Senior Neurologist", experience: "2013-Present" }
    ],
    registration_number: "MMC-99001",
    registration_year: "2004",
    online_fee: "1200",
    clinic_fee: "2000",
    show_fees_on_app: true,
    online_booking_window: "45",
    clinic_booking_window: "15",
    languages: ["English", "Marathi", "Hindi"],
    otherLanguage: "",
    bio: "Expert neurologist treating stroke, epilepsy, headache disorders, and neurodegenerative conditions.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-6677-8899-0011",
    hpid: "HPID654987321",
    registered_date: "2023-08-05",
    account_status: "active",
    application_status: "approve",
    commission: 20
  },
  {
    id: "7890abcd-ef12-3456-7890-abcdef123456",
    firstName: "Meera",
    lastName: "Iyer",
    mobile: "+919844556677",
    email: "dr.meera@eyecareplus.in",
    clinicName: "Vision Clear Eye Clinic",
    address: "34, Cathedral Road",
    area: "Gopalapuram",
    city: "Chennai",
    pincode: "600086",
    state: "Tamil Nadu",
    council: "Tamil Nadu Medical Council",
    specialty: "Ophthalmology",
    experience: "9",
    other_qualification: "DOMS",
    qualifications: [
      { degree: "MBBS", college: "Madras Medical College", completion_year: "2013" },
      { degree: "MS - Ophthalmology", college: "Sankara Nethralaya", completion_year: "2017" }
    ],
    professionals: [
      { institute: "Aravind Eye Hospital", designation: "Consultant Surgeon", experience: "2018-Present" }
    ],
    registration_number: "TMMC-33445",
    registration_year: "2013",
    online_fee: "600",
    clinic_fee: "900",
    show_fees_on_app: true,
    online_booking_window: "15",
    clinic_booking_window: "5",
    languages: ["English", "Tamil"],
    otherLanguage: "French",
    bio: "Specialist in cataract surgery, refractive corrections (LASIK), and comprehensive pediatric eye care.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-7788-9900-1122",
    hpid: "HPID112233445",
    registered_date: "2023-09-18",
    account_status: "inactive",
    application_status: "pending",
    commission: 20
  },
  {
    id: "890abcde-f123-4567-890a-bcdef1234567",
    firstName: "Alok",
    lastName: "Verma",
    mobile: "+919711223344",
    email: "dr.alok@familyclinic.com",
    clinicName: "Verma Family Health Clinic",
    address: "90, Civil Lines",
    area: "Near High Court",
    city: "Lucknow",
    pincode: "226001",
    state: "Uttar Pradesh",
    council: "Uttar Pradesh Medical Council",
    specialty: "General Medicine",
    experience: "20",
    other_qualification: "FICP",
    qualifications: [
      { degree: "MBBS", college: "King George's Medical University", completion_year: "2000" },
      { degree: "MD - General Medicine", college: "IMS BHU Varanasi", completion_year: "2004" }
    ],
    professionals: [
      { institute: "Sahara Hospital", designation: "Senior Consultant Physician", experience: "2010-Present" }
    ],
    registration_number: "UPMC-55667",
    registration_year: "2000",
    online_fee: "500",
    clinic_fee: "800",
    show_fees_on_app: true,
    online_booking_window: "7",
    clinic_booking_window: "3",
    languages: ["English", "Hindi"],
    otherLanguage: "Urdu",
    bio: "Dedicated general physician managing lifestyle diseases like diabetes, hypertension, and infectious illnesses.",
    app_appointment_token_start: "1",
    aadhaar: "[Aadhaar Redacted]",
    abha: "91-8899-0011-2233",
    hpid: "HPID998877665",
    registered_date: "2023-10-22",
    account_status: "suspended",
    application_status: "approve",
    commission: 20
  }
]


